import { getAllSessions } from "@/lib/cookies";
import { getServiceUrlFromHeaders } from "@/lib/service-url";
import { validateAuthRequest, isRSCRequest } from "@/lib/auth-utils";
import { handleOIDCFlowInitiation, handleSAMLFlowInitiation, FlowInitiationParams } from "@/lib/server/flow-initiation";
import { listSessions } from "@/lib/zitadel";
import { Session } from "@zitadel/proto/zitadel/session/v2/session_pb";
import { headers } from "next/headers";
import { NextRequest, NextResponse } from "next/server";

// Connect gRPC NOT_FOUND code, used when an auth request has expired or never
// existed. We surface that as a redirect rather than a 400 — see comment below.
const CONNECT_NOT_FOUND = 5;

function redirectToChooser(_request: NextRequest, reason?: string): NextResponse {
  // Stale browser tabs and external apps polling /login with an expired
  // authRequest are the dominant 4xx generators on this hostname. Returning
  // 400/500 means CrowdSec eventually trips http-bf / http-probing on
  // legitimate user IPs (and the user is left staring at a JSON error). Send
  // them to the chooser instead — they'll start a fresh OIDC request from
  // there. The `reason` query param is purely a log signal; the chooser does
  // not render anything from it today.
  //
  // We build a relative Location header rather than calling
  // NextResponse.redirect(): from a route handler, that helper resolves the
  // URL against the pod's listen address ([::]:3000) instead of the
  // user-facing host. A leading-slash Location is resolved by the browser
  // against the actual origin and works through Traefik unchanged.
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
  const location = reason
    ? `${basePath}/?error=${encodeURIComponent(reason)}`
    : `${basePath}/`;
  return new NextResponse(null, { status: 307, headers: { location } });
}

function isConnectNotFound(error: unknown): boolean {
  return (
    !!error &&
    typeof error === "object" &&
    "code" in error &&
    (error as { code?: unknown }).code === CONNECT_NOT_FOUND
  );
}

async function loadSessions({ serviceUrl, ids }: { serviceUrl: string; ids: string[] }): Promise<Session[]> {
  const response = await listSessions({
    serviceUrl,
    ids: ids.filter((id: string | undefined) => !!id),
  });

  return response?.sessions ?? [];
}

export async function GET(request: NextRequest) {
  const _headers = await headers();
  const { serviceUrl } = getServiceUrlFromHeaders(_headers);

  const searchParams = request.nextUrl.searchParams;

  // Defensive check: block RSC requests early. Keep the 400 — RSC pings are
  // generated by Next itself and never seen by humans.
  if (isRSCRequest(searchParams)) {
    return NextResponse.json({ error: "RSC requests not supported" }, { status: 400 });
  }

  // No usable auth request param — most likely a stale tab or someone landing
  // here directly. Send them to the chooser.
  const requestId = validateAuthRequest(searchParams);
  if (!requestId) {
    return redirectToChooser(request, "no_auth_request");
  }

  const sessionCookies = await getAllSessions();
  const ids = sessionCookies.map((s) => s.id);
  let sessions: Session[] = [];
  if (ids && ids.length) {
    sessions = await loadSessions({ serviceUrl, ids });
  }

  // Flow initiation - delegate to appropriate handler
  const flowParams: FlowInitiationParams = {
    serviceUrl,
    requestId,
    sessions,
    sessionCookies,
    request,
  };

  try {
    if (requestId.startsWith("oidc_")) {
      return await handleOIDCFlowInitiation(flowParams);
    } else if (requestId.startsWith("saml_")) {
      return await handleSAMLFlowInitiation(flowParams);
    } else if (requestId.startsWith("device_")) {
      // Device Authorization is meant to be handled on /device; if someone
      // dropped a device_ id here it's a caller bug, not a user-facing case.
      return NextResponse.json({ error: "Device authorization should use /device endpoint" }, { status: 400 });
    } else {
      // Unknown prefix — same shape as no auth request, send the user home.
      return redirectToChooser(request, "invalid_request_id");
    }
  } catch (error: unknown) {
    // Expired / never-existed auth request: Zitadel returns NOT_FOUND. This is
    // the dominant cause of /login 400/500s in production (stale tabs, apps
    // polling old authRequest IDs). Redirect instead of erroring so CrowdSec's
    // http-bf scenarios stop tripping on legitimate IPs.
    if (isConnectNotFound(error)) {
      return redirectToChooser(request, "auth_request_not_found");
    }
    throw error;
  }
}
